server:
  port: 8888
spring:
  application:
    #应用的名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wmshopp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: chenyin123
  # 邮箱配置
  mail:
    host: smtp.qq.com  # 发送邮件的服务器地址
    username: 1340599509@qq.com # 登录qq邮箱的账号
    password: tonnmaotwehnjjjb  # 开启 IMAP/SMTP服务 获得的授权码,而不是qq邮箱的登录密码
    default-encoding: UTF-8
  # redis配置
  redis:
    host: localhost # 本地IP 或是 虚拟机IP
    port: 6379
    #    password: root
    database: 0  # 默认使用 0号db
    cache:
      redis:
        time-to-live: 1800000  # 设置缓存数据的过期时间，30分钟

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
    # 设置逻辑删除（也可不写，如果逻辑和如下一样，可以不写的）
    logic-delete-value: 1
    logic-not-delete-value: 0

# 图片存储路径
reggie:
  path: D:\Desktop\FoodShopping\